global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # FastAPI application
  - job_name: 'disease-outbreak-api'
    static_configs:
      - targets: ['localhost:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # MLflow
  - job_name: 'mlflow'
    static_configs:
      - targets: ['localhost:5000']
    scrape_interval: 30s

  # Kafka
  - job_name: 'kafka'
    static_configs:
      - targets: ['localhost:9101']
    scrape_interval: 30s

  # Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['localhost:6379']
    scrape_interval: 30s

  # PostgreSQL
  - job_name: 'postgres'
    static_configs:
      - targets: ['localhost:5432']
    scrape_interval: 30s

  # Node exporter (if available)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['localhost:9100']
    scrape_interval: 30s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - localhost:9093

# Recording rules for common queries
rule_files:
  - "rules/outbreak_alerts.yml"
  - "rules/system_health.yml"
