# Model configuration
model:
  name: "disease_outbreak_predictor"
  version: "1.0.0"
  stage: "Staging"
  description: "Random Forest model for predicting disease outbreak risks"
  tags:
    framework: "scikit-learn"
    task: "classification"
    owner: "ml-team"
  hyperparameters:
    n_estimators: 100
    max_depth: 10
    min_samples_split: 2
    min_samples_leaf: 1
    random_state: 42
  metrics:
    accuracy: 0.0
    precision: 0.0
    recall: 0.0
    f1: 0.0
    roc_auc: 0.0

# Data configuration
data:
  train_path: "data/processed/train.parquet"
  test_path: "data/processed/test.parquet"
  validation_path: "data/processed/validation.parquet"
  feature_columns:
    - "temperature"
    - "humidity"
    - "rainfall"
    - "population_density"
    - "avg_historical_cases"
    - "case_trend"
    - "social_media_mentions"
  target_column: "outbreak_risk"
  validation_expectations_path: "data/expectations/validation_expectations.json"

# Training configuration
training:
  experiment_name: "disease-outbreak-classification"
  run_name: "random_forest_v1"
  max_epochs: 100
  batch_size: 32
  learning_rate: 0.001
  early_stopping_patience: 5
  validation_metric: "val_loss"
  validation_mode: "min"

# Validation configuration
validation:
  min_accuracy: 0.75
  max_false_positive_rate: 0.25
  max_drift_score: 0.15
  test_size: 0.2
  random_state: 42

# MLflow configuration
mlflow:
  tracking_uri: "http://localhost:5000"
  registry_uri: "s3://mlflow-models/"
  artifact_location: "s3://mlflow-artifacts/disease-outbreak/"
  experiment_name: "disease-outbreak"

# Pipeline configuration
output_dir: "models/disease_outbreak"
log_level: "INFO"
